/**
 * SemText — canonical record extraction.
 *
 * Normative contract: spec/extraction.md
 * BDD source of truth:  test/e2e/extraction.cy.js
 *
 * Extraction projects a SemText document to a flat, ordered array of records.
 * It is PURE: it never writes an attribute, never inserts or removes a node,
 * never dispatches an event. It reads only authored semantics — generated
 * chrome, runtime state classes, and mutable presentation attributes
 * (`data-active`, `collapsed`, `data-view-as`) are deliberately invisible to
 * it. That is what makes the central invariant hold: the same document
 * yields the same records with JS on, with JS off, under any `view-as`, and
 * after arbitrary interaction.
 *
 * No runtime dependencies, no fetch, no top-level await — bundles to a
 * classic IIFE script.
 */

import { deriveSummary } from '../shared/summary.js';
import { normalizeMd } from '../shared/mdsource.js';
import { parseMarks } from '../shared/marks.js';

/** One extracted record. Shape is normative; see spec/extraction.md §2. */
export interface SemRecord {
  /** Vocabulary token, normalized across authoring forms (`sem-fact`), or
   *  the lowercased tag name for a minted plain-HTML record. */
  type: string;
  /** `id` attribute, or null. Citation token. */
  id: string | null;
  /** `data-kind` / `kind`, or null. */
  kind: string | null;
  /** `data-tags` / `tags` split on commas; [] when absent. */
  tags: string[];
  /** `data-audience` / `audience` verbatim, or null. Never parsed, never
   *  used to suppress a record (spec/schema/sem-audiences.md). */
  audience: string | null;
  /** `sourceOrder` of the nearest enclosing record, or null at top level. */
  parent: number | null;
  /** Per-type semantic payload; see §4 of the spec. */
  fields: Record<string, unknown>;
  /** One-line human rendering of this record's own assertion. */
  text: string;
  /** 0-based document-order position. Equals the index in the array. */
  sourceOrder: number;
}

/* ------------------------------------------------------------------ *
 * Vocabulary tables
 * ------------------------------------------------------------------ */

/** Elements that mint a record, keyed by normalized type token. */
const RECORD_TYPES = [
  'sem-agent',
  'sem-note',
  'sem-facts',
  'sem-fact',
  'sem-details',
  'sem-detail',
  'sem-procedure',
  'sem-step',
  'sem-properties',
  'sem-property',
  'sem-views',
  'sem-view',
  'sem-reveal',
  'sem-progress',
  // R/W1 prose elements (spec/schema/sem-chronology.md, sem-code.md,
  // sem-references.md)
  'sem-chronology',
  'sem-event',
  'sem-code',
  'sem-references',
  'sem-reference',
  // R/W2 (spec/schema/sem-table.md); sem-reader is chrome and is NOT here
  'sem-table',
  // R/W2.2 (spec/schema/sem-md.md)
  'sem-md'
] as const;

/**
 * Chrome ELEMENTS — skipped whole, like the generated chrome classes, but
 * addressed by vocabulary name because they are authored: `sem-reader`
 * (spec/schema/sem-reader.md) mints nothing, and neither does its authored
 * `<nav aria-label="Contents">` child (spec/extraction.md §3 rule 7).
 */
const CHROME_TYPES = ['sem-reader'];

/** v0.3 custom-element tag names that are not simply `sem-<type>`. */
const TAG_ALIASES: Record<string, string> = { agent: 'sem-agent' };

/**
 * Chrome and state nodes generated by the fallback handler or the Lit
 * upgrade. Never contribute text, never mint records.
 */
const CHROME_CLASSES = [
  'sem-facts-chrome',
  'sem-facts-meter',
  'sem-quiz-options',
  'sem-views-tabs',
  'sem-note-summary',
  'sem-progress-track',
  'sem-progress-fill',
  // reading bundle (R/W1)
  'sem-code-chrome',
  'sem-code-status',
  'sem-references-backlinks',
  'sem-references-link',
  'sem-popover',
  // R/W2
  'sem-reader-chrome',
  'sem-reader-outline',
  'sem-reader-progress',
  'sem-table-chrome',
  'sem-table-status',
  'sem-table-filter',
  // sem-source: the toggle chrome, the derived fence (and the sem-code in
  // it) and the core's template snapshot are never content
  'sem-source-chrome',
  'sem-source-fence',
  'sem-source-raw',
  // sem-md: the toggle/copy chrome, the rendered body and the raw fence
  // (the sem-code inside it included) are never content
  'sem-md-chrome',
  'sem-md-body',
  'sem-md-raw'
];

/** Highlight / cloze markers, in every authoring and runtime form. */
const HIGHLIGHT_CLASSES = ['sem-highlight', 'sem-occluded'];

/* ------------------------------------------------------------------ *
 * Small DOM helpers (no library, no mutation)
 * ------------------------------------------------------------------ */

function tagOf(el: Element): string {
  return el.tagName.toLowerCase();
}

function hasClass(el: Element, name: string): boolean {
  const cls = el.getAttribute('class');
  if (!cls) return false;
  return (' ' + cls + ' ').indexOf(' ' + name + ' ') >= 0;
}

/**
 * Read a parameter in either authoring form: v0.4 `data-<name>` on a
 * classed div, or v0.3 bare `<name>` on a custom element. `data-` wins.
 */
function param(el: Element, name: string): string | null {
  const d = el.getAttribute('data-' + name);
  if (d !== null) return d;
  return el.getAttribute(name);
}

function hasParam(el: Element, name: string): boolean {
  return el.hasAttribute('data-' + name) || el.hasAttribute(name);
}

/** Collapse all whitespace runs to a single space and trim. */
function norm(s: string): string {
  return s.replace(/\s+/g, ' ').trim();
}

function isChrome(el: Element): boolean {
  for (let i = 0; i < CHROME_CLASSES.length; i++) {
    if (hasClass(el, CHROME_CLASSES[i])) return true;
  }
  for (let i = 0; i < CHROME_TYPES.length; i++) {
    if (tagOf(el) === CHROME_TYPES[i] || hasClass(el, CHROME_TYPES[i])) return true;
  }
  // The <summary> the reveal fallback synthesizes inside its <details>.
  // Narrowly scoped: an authored <details>/<summary> elsewhere is content.
  if (tagOf(el) === 'summary') {
    const details = el.parentElement;
    if (details && tagOf(details) === 'details') {
      const host = details.parentElement;
      if (host && (hasClass(host, 'sem-reveal') || tagOf(host) === 'sem-reveal')) {
        return true;
      }
    }
  }
  return false;
}

function isHighlight(el: Element): boolean {
  if (tagOf(el) === 'highlight') return true;
  for (let i = 0; i < HIGHLIGHT_CLASSES.length; i++) {
    if (hasClass(el, HIGHLIGHT_CLASSES[i])) return true;
  }
  return false;
}

/** Normalized record type for an element, or null when it mints nothing. */
function recordType(el: Element): string | null {
  const tag = tagOf(el);
  if (TAG_ALIASES[tag]) return TAG_ALIASES[tag];
  for (let i = 0; i < RECORD_TYPES.length; i++) {
    const t = RECORD_TYPES[i];
    if (tag === t) return t;
    if (hasClass(el, t)) return t;
  }
  return null;
}

/**
 * The minting test: plain semantic HTML carrying an sem global qualifier
 * (`kind` or `tags`) is a record too. `id` alone does not mint — ids are
 * ubiquitous anchors, not semantic claims.
 */
function mintsPlainRecord(el: Element): boolean {
  if (hasClass(el, 'sem-enhanced-document')) return false;
  // sem-source is a transparent wrapper: never a record, whatever it carries
  if (hasClass(el, 'sem-source')) return false;
  if (tagOf(el).indexOf('sem-') === 0) return false;
  // The <table> inside a sem-table is the wrapper's contract, not a second
  // record — its `kind` (comparison) is a CSS hook (spec/schema/sem-table.md).
  if (tagOf(el) === 'table') {
    const p = el.parentElement;
    if (p && (tagOf(p) === 'sem-table' || hasClass(p, 'sem-table'))) return false;
  }
  return hasParam(el, 'kind') || hasParam(el, 'tags');
}

/* ------------------------------------------------------------------ *
 * Text collection
 * ------------------------------------------------------------------ */

type SkipFn = (el: Element) => boolean;

/**
 * Concatenate the text of `el`, descending through inline markup but
 * skipping any element `skip` rejects. Raw concatenation preserves the
 * authored spacing; `norm` collapses it afterwards.
 */
function collectText(el: Element, skip: SkipFn): string {
  let out = '';
  const nodes = el.childNodes;
  for (let i = 0; i < nodes.length; i++) {
    const n = nodes[i];
    if (n.nodeType === 3) {
      out += n.nodeValue || '';
    } else if (n.nodeType === 1) {
      const child = n as Element;
      if (skip(child)) continue;
      out += collectText(child, skip);
    }
  }
  return out;
}

/** Skip generated chrome and any nested record (which gets its own entry). */
function proseSkip(el: Element): boolean {
  return isChrome(el) || recordType(el) !== null || mintsPlainRecord(el);
}

function prose(el: Element): string {
  return norm(collectText(el, proseSkip));
}

/** Direct-ish part lookup: `.sem-x` (v0.4) or `<x>` (v0.3), first match. */
function part(el: Element, cls: string, tag: string): Element | null {
  const list = el.querySelectorAll(tag + ', .' + cls);
  for (let i = 0; i < list.length; i++) {
    const cand = list[i];
    if (nearestRecordAncestor(cand, el) === el) return cand;
  }
  return null;
}

function parts(el: Element, cls: string, tag: string): Element[] {
  const out: Element[] = [];
  const list = el.querySelectorAll(tag + ', .' + cls);
  for (let i = 0; i < list.length; i++) {
    if (nearestRecordAncestor(list[i], el) === el) out.push(list[i]);
  }
  return out;
}

/**
 * Walk up from `el` (exclusive) to `stop` (inclusive) and return the first
 * ancestor that is itself a record — used to keep a container's part
 * lookups from reaching into a nested record's parts.
 */
function nearestRecordAncestor(el: Element, stop: Element): Element | null {
  let cur: Element | null = el.parentElement;
  while (cur) {
    if (cur === stop) return stop;
    if (recordType(cur) !== null || mintsPlainRecord(cur)) return cur;
    cur = cur.parentElement;
  }
  return null;
}

function partText(el: Element, cls: string, tag: string): string | null {
  const p = part(el, cls, tag);
  return p ? norm(collectText(p, isChrome)) : null;
}

function highlightsIn(el: Element): string[] {
  const out: string[] = [];
  const list = el.querySelectorAll('highlight, .sem-highlight, .sem-occluded');
  for (let i = 0; i < list.length; i++) {
    const h = list[i];
    if (nearestRecordAncestor(h, el) !== el) continue;
    if (!isHighlight(h)) continue;
    out.push(norm(collectText(h, isChrome)));
  }
  return out;
}

/* ------------------------------------------------------------------ *
 * Derivations
 * ------------------------------------------------------------------ */

/** Compact `term :: value` sugar. Returns null when the separator is absent. */
function splitCompact(text: string): { left: string; right: string } | null {
  const i = text.indexOf('::');
  if (i < 0) return null;
  return { left: norm(text.slice(0, i)), right: norm(text.slice(i + 2)) };
}

/**
 * Normative derived summary for `sem-reveal` without `data-summary` lives in
 * `shared/summary` so the fallback's `<summary>` and this field agree.
 * Re-exported for consumers that imported it from here.
 */
export { deriveSummary } from '../shared/summary.js';

function clamp01(raw: string | null): number {
  const n = raw === null ? NaN : parseFloat(raw);
  if (isNaN(n)) return 0;
  return Math.min(1, Math.max(0, n));
}

function tagList(el: Element): string[] {
  const raw = param(el, 'tags');
  if (!raw) return [];
  const out: string[] = [];
  const pieces = raw.split(',');
  for (let i = 0; i < pieces.length; i++) {
    const t = pieces[i].trim();
    if (t) out.push(t);
  }
  return out;
}

/** Position of `el` among siblings sharing its record type. */
function ordinalAmongSiblings(el: Element, type: string): number {
  const parentEl = el.parentElement;
  if (!parentEl) return 1;
  let n = 0;
  const kids = parentEl.children;
  for (let i = 0; i < kids.length; i++) {
    if (recordType(kids[i]) === type) {
      n++;
      if (kids[i] === el) return n;
    }
  }
  return n || 1;
}

/* ------------------------------------------------------------------ *
 * Per-type field mapping
 * ------------------------------------------------------------------ */

interface Payload {
  fields: Record<string, unknown>;
  text: string;
}

function buildAgent(el: Element): Payload {
  const name = partText(el, 'sem-agent-name', 'name') || '';
  const bio = partText(el, 'sem-agent-bio', 'bio') || '';
  const instructions = partText(el, 'sem-agent-instructions', 'instructions') || '';
  return { fields: { name, bio, instructions }, text: name };
}

function buildNote(el: Element): Payload {
  const variant = param(el, 'variant') || 'info';
  const body = part(el, 'sem-note-body', 'sem-note-body');
  const text = body ? norm(collectText(body, isChrome)) : prose(el);
  return { fields: { variant }, text };
}

function buildFact(el: Element): Payload {
  let statement = partText(el, 'sem-statement', 'statement');
  let conclusion = partText(el, 'sem-conclusion', 'conclusion');
  const distractors: string[] = [];
  const ds = parts(el, 'sem-distractor', 'sem-distractor');
  for (let i = 0; i < ds.length; i++) {
    distractors.push(norm(collectText(ds[i], isChrome)));
  }

  if (statement === null && conclusion === null) {
    // Compact form: `statement :: conclusion`, distractors excluded.
    const raw = norm(
      collectText(el, function (child) {
        return (
          isChrome(child) ||
          hasClass(child, 'sem-distractor') ||
          tagOf(child) === 'sem-distractor'
        );
      })
    );
    const split = splitCompact(raw);
    if (split) {
      statement = split.left;
      conclusion = split.right;
    } else {
      statement = raw;
    }
  }

  const fields: Record<string, unknown> = {
    statement: statement || '',
    conclusion: conclusion || '',
    distractors: distractors,
    highlights: highlightsIn(el)
  };
  const text = conclusion ? statement + ' :: ' + conclusion : statement || '';
  return { fields: fields, text: text };
}

function buildDetail(el: Element): Payload {
  return { fields: { highlights: highlightsIn(el) }, text: prose(el) };
}

function buildStep(el: Element): Payload {
  const status = param(el, 'status') || 'todo';
  const ordinal = ordinalAmongSiblings(el, 'sem-step');
  return { fields: { status: status, ordinal: ordinal }, text: prose(el) };
}

function buildProperty(el: Element): Payload {
  let key = param(el, 'key');
  let value = prose(el);
  if (key === null) {
    const split = splitCompact(value);
    if (split) {
      key = split.left;
      value = split.right;
    }
  }
  key = key === null ? '' : norm(key);
  return {
    fields: { key: key, value: value },
    text: key ? key + ' :: ' + value : value
  };
}

function buildView(el: Element): Payload {
  const name = param(el, 'name') || '';
  const index = ordinalAmongSiblings(el, 'sem-view') - 1;
  return { fields: { name: name, index: index }, text: prose(el) };
}

function buildProgress(el: Element): Payload {
  const raw = param(el, 'value');
  const value = clamp01(raw);
  const label = param(el, 'label') || 'progress';
  const status = param(el, 'status');
  const fields: Record<string, unknown> = {
    value: value,
    rawValue: raw === null ? '' : raw,
    label: label
  };
  if (status !== null) fields.status = status;
  // Text is DERIVED, never read from the DOM: the fallback overwrites the
  // element's text content when it renders the meter.
  return { fields: fields, text: label + ' :: ' + Math.round(value * 100) + '%' };
}

function buildReveal(el: Element): Payload {
  // JS-on the fallback moves the body into `.sem-reveal-body` inside a
  // <details> and prepends a <summary>. Unwrap the body, ignore the summary.
  const bodyEl = el.querySelector('.sem-reveal-body') || el;
  const text = norm(collectText(bodyEl, proseSkip));
  const authored = param(el, 'summary');
  const summary = authored !== null ? norm(authored) : deriveSummary(text);
  return {
    fields: {
      summary: summary,
      summarySource: authored !== null ? 'authored' : 'derived'
    },
    text: text
  };
}

function buildEvent(el: Element): Payload {
  const fields: Record<string, unknown> = {
    when: param(el, 'when') || '',
    until: param(el, 'until') || '',
    ordinal: ordinalAmongSiblings(el, 'sem-event')
  };
  // An event is a record of something that happened, not a task: no
  // default status (contrast sem-step's `todo`).
  const status = param(el, 'status');
  if (status !== null) fields.status = status;
  return { fields: fields, text: prose(el) };
}

function buildCode(el: Element): Payload {
  // `source` is VERBATIM — the one field whose whitespace is content
  // (spec/schema/sem-code.md, machine contract). Line-wrapping spans and
  // <mark> are read through; chrome is skipped.
  const pre = el.querySelector('pre');
  const code = pre ? pre.querySelector('code') || pre : null;
  const source = code ? collectText(code, isChrome) : '';
  const lines = source === '' ? 0 : source.split('\n').length;
  return {
    fields: {
      lang: param(el, 'lang') || '',
      filename: param(el, 'filename') || '',
      marks: parseMarks(param(el, 'mark'), lines),
      source: source
    },
    text: norm(source)
  };
}

function buildMd(el: Element): Payload {
  // `source` is the NORMALISED Markdown (spec/schema/sem-md.md, machine
  // contract): once enhanced, the element's text lives in the raw fence's
  // <code> (byte-identical to what the renderer saw); JS-off it is the
  // element's own text, which the same normalisation reduces to the same
  // string. Chrome, body and fence are skipped by the walker; the fence is
  // read here on purpose.
  const fence = el.querySelector(':scope > .sem-md-raw code');
  // normalised on BOTH paths (idempotent on an already-normalised fence),
  // so the invariant does not rest on the fence staying byte-identical
  const source = normalizeMd(collectText(fence || el, isChrome));
  return { fields: { source: source }, text: norm(source) };
}

function buildReference(el: Element): Payload {
  return {
    fields: {
      href: param(el, 'href') || '',
      cite: param(el, 'cite') || '',
      ordinal: ordinalAmongSiblings(el, 'sem-reference')
    },
    text: prose(el)
  };
}

function buildTable(el: Element): Payload {
  // Rows come back in AUTHORED order: the reading bundle stamps
  // `data-sem-source-index` before its sort ever moves a row, so the
  // stamp — not DOM order — is the order (spec/extraction.md §5, recorded
  // exception). `hidden` (filter) is never consulted.
  // Scoped selectors throughout: a table nested inside a cell is that
  // cell's content, and only the first header row names the columns.
  const table = el.querySelector(':scope > table');
  const cellText = function (c: Element): string { return norm(collectText(c, proseSkip)); };
  const columns: string[] = [];
  const rows: string[][] = [];
  let caption = '';
  if (table) {
    const cap = table.querySelector(':scope > caption');
    if (cap) caption = norm(collectText(cap, isChrome));
    const heads = table.querySelectorAll(':scope > thead > tr:first-of-type > :is(th, td)');
    for (let i = 0; i < heads.length; i++) columns.push(cellText(heads[i]));
    const trs: { tr: Element; idx: number }[] = [];
    const list = table.querySelectorAll(':scope > tbody > tr');
    for (let i = 0; i < list.length; i++) {
      const raw = list[i].getAttribute('data-sem-source-index');
      const idx = raw === null ? NaN : parseInt(raw, 10);
      trs.push({ tr: list[i], idx: isNaN(idx) ? i : idx });
    }
    trs.sort(function (a, b) { return a.idx - b.idx; });
    for (let i = 0; i < trs.length; i++) {
      const cells = trs[i].tr.children;
      const row: string[] = [];
      for (let k = 0; k < cells.length; k++) row.push(cellText(cells[k]));
      rows.push(row);
    }
  }
  return { fields: { caption: caption, columns: columns, rows: rows }, text: caption };
}

function buildContainer(el: Element): Payload {
  return { fields: {}, text: '' };
}

function buildPlain(el: Element): Payload {
  return { fields: {}, text: prose(el) };
}

function payloadFor(type: string, el: Element): Payload {
  switch (type) {
    case 'sem-agent':
      return buildAgent(el);
    case 'sem-note':
      return buildNote(el);
    case 'sem-fact':
      return buildFact(el);
    case 'sem-detail':
      return buildDetail(el);
    case 'sem-step':
      return buildStep(el);
    case 'sem-property':
      return buildProperty(el);
    case 'sem-view':
      return buildView(el);
    case 'sem-progress':
      return buildProgress(el);
    case 'sem-reveal':
      return buildReveal(el);
    case 'sem-event':
      return buildEvent(el);
    case 'sem-code':
      return buildCode(el);
    case 'sem-reference':
      return buildReference(el);
    case 'sem-md':
      return buildMd(el);
    case 'sem-table':
      return buildTable(el);
    case 'sem-facts':
    case 'sem-details':
    case 'sem-procedure':
    case 'sem-properties':
    case 'sem-views':
    case 'sem-chronology':
    case 'sem-references':
      return buildContainer(el);
    default:
      return buildPlain(el);
  }
}

/* ------------------------------------------------------------------ *
 * Walk
 * ------------------------------------------------------------------ */

function rootElement(root: Document | Element): Element | null {
  const doc = (root as Document).nodeType === 9 ? (root as Document) : null;
  if (!doc) return root as Element;
  const scoped = doc.querySelector('.sem-enhanced-document, sem-enhanced-document');
  return scoped || doc.body || doc.documentElement;
}

/**
 * Extract the canonical record array from a document or a root element,
 * in document order. Pure: the DOM is not modified.
 */
export function extractRecords(root: Document | Element): SemRecord[] {
  const start = rootElement(root);
  const out: SemRecord[] = [];
  if (!start) return out;

  function visit(el: Element, parentIndex: number | null): void {
    if (isChrome(el)) return;

    let index = parentIndex;
    const type = recordType(el) || (mintsPlainRecord(el) ? tagOf(el) : null);

    if (type !== null) {
      const payload = payloadFor(type, el);
      const record: SemRecord = {
        type: type,
        id: el.getAttribute('id'),
        kind: param(el, 'kind'),
        tags: tagList(el),
        audience: param(el, 'audience'),
        parent: parentIndex,
        fields: payload.fields,
        text: payload.text,
        sourceOrder: out.length
      };
      out.push(record);
      index = record.sourceOrder;
    }

    const kids = el.children;
    for (let i = 0; i < kids.length; i++) visit(kids[i], index);
  }

  // The root wrapper delimits scope; it is not itself a record.
  if (recordType(start) !== null || mintsPlainRecord(start)) {
    visit(start, null);
  } else {
    const kids = start.children;
    for (let i = 0; i < kids.length; i++) visit(kids[i], null);
  }
  return out;
}

/* ------------------------------------------------------------------ *
 * Plain-text renderer (conventions.md §8 reference recipe)
 * ------------------------------------------------------------------ */

function depthOf(records: SemRecord[], record: SemRecord): number {
  let d = 0;
  let p = record.parent;
  while (p !== null && d < 32) {
    d++;
    p = records[p].parent;
  }
  return d;
}

function annotate(record: SemRecord): string {
  const bits: string[] = [];
  if (record.id) bits.push('#' + record.id);
  if (record.kind) bits.push('kind=' + record.kind);
  if (record.tags.length) bits.push('tags=' + record.tags.join('|'));
  if (record.audience) bits.push('audience=' + record.audience);
  return bits.length ? ' (' + bits.join(' ') + ')' : '';
}

const TEXTUAL_FIELDS: Record<string, string[]> = {
  'sem-agent': ['bio', 'instructions'],
  'sem-note': ['variant'],
  'sem-fact': ['distractors'],
  'sem-detail': ['highlights'],
  'sem-step': ['status'],
  'sem-progress': ['rawValue'],
  'sem-reveal': ['summary'],
  'sem-view': ['name'],
  'sem-property': [],
  'sem-event': ['when', 'until', 'status'],
  'sem-code': ['lang', 'filename'],
  'sem-reference': ['href', 'cite'],
  'sem-table': ['columns'],
  'sem-md': []
};

/**
 * Render records as annotated plain text for terminal / LLM pipelines.
 * Same purity guarantee as `extractRecords`; same invariance.
 */
export function renderRecordsAsText(records: SemRecord[]): string {
  const lines: string[] = [];
  for (let i = 0; i < records.length; i++) {
    const r = records[i];
    const pad = new Array(depthOf(records, r) + 1).join('  ');
    let head = pad + r.type + annotate(r);
    // sem-code and sem-md render their verbatim source as a block below
    // instead of repeating the normalised text on the head line.
    const block = r.type === 'sem-code' || r.type === 'sem-md';
    if (r.text && !block) head += ': ' + r.text;
    lines.push(head);

    const extra = TEXTUAL_FIELDS[r.type] || [];
    for (let k = 0; k < extra.length; k++) {
      const key = extra[k];
      const v = r.fields[key];
      if (v === undefined || v === null || v === '') continue;
      if (Object.prototype.toString.call(v) === '[object Array]') {
        const arr = v as string[];
        if (!arr.length) continue;
        lines.push(pad + '  ' + key + ': ' + arr.join(' | '));
      } else {
        lines.push(pad + '  ' + key + ': ' + String(v));
      }
    }
    if (r.type === 'sem-table') {
      const rows = r.fields.rows as string[][];
      for (let k = 0; k < rows.length; k++) lines.push(pad + '    ' + rows[k].join(' | '));
    }
    if (block) {
      const src = String(r.fields.source || '');
      if (src !== '') {
        lines.push(pad + '  source:');
        const srcLines = src.split('\n');
        for (let k = 0; k < srcLines.length; k++) lines.push(pad + '    ' + srcLines[k]);
      }
    }
  }
  return lines.join('\n');
}

/** DOM → annotated plain text, in one call. */
export function extractText(root: Document | Element): string {
  return renderRecordsAsText(extractRecords(root));
}
